#!/usr/bin/env python3
from datetime import datetime
from render import render_template as render
import json


def format_date(date_str):
    date = datetime.strptime(date_str, "%Y-%m-%d")
    suffixes = {1:'st',2:'nd',3:'rd'}
    suffix = 'th' if 11 <= date.day <= 13 else suffixes.get(date.day % 10, 'th')
    return date.strftime("%B {}{}, %Y").format(date.day, suffix)


if __name__ == "__main__":
    with open("posts.json") as posts_file:
        posts = json.load(posts_file)

    for post in posts:
        print(f"Rendering Post: {post['TITLE']}")
        with open(post['OUTPUT'], 'w') as fout:
            post['PRETTY_DATE'] = format_date(post['DATE'])
            fout.write(render("templates/post.html", {"post": post}))

    print("Rendering index")
    visible_posts = sorted(
        [p for p in posts if not p.get("HIDE")],
        key=lambda p: p['DATE'],
        reverse=True
    )
    with open("index.html", 'w') as fout:
        fout.write(render("templates/index.html", {"posts": visible_posts}))
