#!/usr/bin/env python3
import re
import sys
from subprocess import check_output


def replace_many(s, olds, news):
    for old, new in zip(olds, news):
        s = s.replace(old, new, 1)
    return s


if __name__ == "__main__":
    with open(sys.argv[1]) as fin:
        template = fin.read()

    code_blocks = re.findall(r"{{.*?}}", template, re.S)
    rendered = (check_output(block[2:-2], shell=True).decode("UTF-8") for block in code_blocks)
    print(replace_many(template, code_blocks, rendered))
